[package]
name = "word_counter"
version = "0.1.0"
edition = "2018"

[dependencies]
napi = "0.4"
napi-derive = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
voca_rs = "1.10.1"

[build-dependencies]
napi-build = "0.2"

[lib]
crate-type = ["cdylib"]

